baseURL = "www.example.com"
languageCode = "en-us"
title = "Bryan Guner Lambda Resources"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.homepage]
  show_call_box = true
  hide_view_all_services = true

  [params.logo]
  mobile = "images/logo/logo-mobile.svg"
  mobile_height = "36px"
  desktop = "images/webdevhub.PNG"
  desktop_height = "36px"
  alt = "Serif - A Hugo Business Theme"

  [params.homepage_meta_tags]
  meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_og_title = "Hugo Serif Theme"
  meta_og_type = "website"
  meta_og_url = "https://hugo-serif.netlify.app"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

  [params.team]
  summary_large_truncate = 120

[[menu.main]]
name = "Projects"
url = "https://lambda-static-resources.netlify.app/1-projects/directory.html"
weight = 1

[[menu.main]]
name = "Content"
url = "https://lambda-static-resources.netlify.app/2-content/directory.html"
weight = 2

[[menu.main]]
name = "Resources"
url = "https://lambda-static-resources.netlify.app/2-resources/directory.html"
weight = 3

[[menu.main]]
name = "Blog"
url = "https://best-celery-b2d7c.netlify.app/docs/links/"
weight = 4

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
